# Generated by Django 3.2.20 on 2025-09-25 21:18

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('external_key', models.IntegerField()),
                ('source', models.CharField(max_length=256)),
                ('sponsor_pi', models.CharField(max_length=512)),
                ('billing_contact', models.CharField(max_length=512)),
                ('fileset_name', models.CharField(max_length=256)),
                ('service_rate_category', models.CharField(max_length=256)),
                ('usage', models.CharField(max_length=256)),
                ('funding_number', models.CharField(max_length=256)),
                ('exempt', models.BooleanField()),
                ('subsidized', models.BooleanField()),
                ('is_condo_group', models.BooleanField()),
                ('parent_id_key', models.IntegerField()),
                ('quota', models.CharField(max_length=256)),
                ('billing_cycle', models.CharField(max_length=256)),
                ('usage_timestamp', models.DateTimeField()),
                ('ingestion_date', models.DateTimeField()),
                ('storage_cluster', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
