# Generated by Django 3.2.20 on 2025-11-04 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('external_key', models.IntegerField()),
                ('source', models.CharField(max_length=256)),
                ('tier', models.CharField(max_length=256)),
                ('sponsor_pi', models.CharField(max_length=512)),
                ('billing_contact', models.CharField(max_length=512)),
                ('fileset_name', models.CharField(max_length=256)),
                ('service_rate_category', models.CharField(max_length=256)),
                ('usage_tb', models.DecimalField(decimal_places=6, max_digits=20)),
                ('funding_number', models.CharField(max_length=256)),
                ('exempt', models.BooleanField()),
                ('subsidized', models.BooleanField()),
                ('is_condo_group', models.BooleanField()),
                ('parent_id_key', models.IntegerField(blank=True, null=True)),
                ('quota', models.CharField(max_length=256)),
                ('billing_cycle', models.CharField(max_length=256)),
                ('usage_date', models.DateField()),
                ('storage_cluster', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['tier', 'usage_date', 'sponsor_pi', 'service_rate_category', 'fileset_name'],
                'unique_together': {('tier', 'storage_cluster', 'fileset_name', 'usage_date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyStorageBilling',
            fields=[
                ('allocationusage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='billing.allocationusage')),
            ],
            options={
                'managed': False,
            },
            bases=('billing.allocationusage',),
        ),
        migrations.CreateModel(
            name='HistoricalAllocationUsage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('external_key', models.IntegerField()),
                ('source', models.CharField(max_length=256)),
                ('tier', models.CharField(max_length=256)),
                ('sponsor_pi', models.CharField(max_length=512)),
                ('billing_contact', models.CharField(max_length=512)),
                ('fileset_name', models.CharField(max_length=256)),
                ('service_rate_category', models.CharField(max_length=256)),
                ('usage_tb', models.DecimalField(decimal_places=6, max_digits=20)),
                ('funding_number', models.CharField(max_length=256)),
                ('exempt', models.BooleanField()),
                ('subsidized', models.BooleanField()),
                ('is_condo_group', models.BooleanField()),
                ('parent_id_key', models.IntegerField(blank=True, null=True)),
                ('quota', models.CharField(max_length=256)),
                ('billing_cycle', models.CharField(max_length=256)),
                ('usage_date', models.DateField()),
                ('storage_cluster', models.CharField(max_length=256)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical allocation usage',
                'verbose_name_plural': 'historical allocation usages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
