# Generated by Django 3.2.20 on 2025-09-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_historicalallocationusage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocationusage',
            options={'ordering': ['usage_timestamp', 'sponsor_pi', 'service_rate_category']},
        ),
    ]
