# Generated by Django 3.2.20 on 2025-09-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_allocationusage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationusage',
            name='usage',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicalallocationusage',
            name='usage',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
    ]
