# Generated by Django 3.2.20 on 2025-09-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20250930_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationusage',
            name='parent_id_key',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allocationusage',
            name='usage',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicalallocationusage',
            name='parent_id_key',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocationusage',
            name='usage',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
