default_aces = [
    {
        "flags": ["CONTAINER_INHERIT"],
        "type": "ALLOWED",
        "trustee": {"name": "File Owner"},
        "rights": [
            "READ",
            "ADD_FILE",
            "ADD_SUBDIR",
            "SYNCHRONIZE",
            "READ_ACL",
            "READ_ATTR",
            "READ_EA",
            "DELETE_CHILD",
            "CHANGE_OWNER",
            "EXECUTE",
            "WRITE_ACL",
            "WRITE_ATTR",
            "WRITE_EA",
        ],
    },
    {
        "flags": ["OBJECT_INHERIT"],
        "type": "ALLOWED",
        "trustee": {"name": "File Owner"},
        "rights": [
            "READ",
            "ADD_FILE",
            "ADD_SUBDIR",
            "SYNCHRONIZE",
            "READ_ACL",
            "READ_ATTR",
            "READ_EA",
            "CHANGE_OWNER",
            "WRITE_ACL",
            "WRITE_ATTR",
            "WRITE_EA",
        ],
    },
    {
        "flags": ["CONTAINER_INHERIT"],
        "type": "ALLOWED",
        "trustee": {"name": "ris-it-admin", "domain": "ACTIVE_DIRECTORY"},
        "rights": [
            "READ",
            "ADD_FILE",
            "ADD_SUBDIR",
            "SYNCHRONIZE",
            "READ_ACL",
            "READ_ATTR",
            "READ_EA",
            "EXECUTE",
            "DELETE_CHILD",
            "WRITE_ATTR",
            "WRITE_EA",
        ],
    },
    {
        "flags": ["OBJECT_INHERIT"],
        "type": "ALLOWED",
        "trustee": {"name": "ris-it-admin", "domain": "ACTIVE_DIRECTORY"},
        "rights": [
            "READ",
            "ADD_FILE",
            "ADD_SUBDIR",
            "SYNCHRONIZE",
            "READ_ACL",
            "READ_ATTR",
            "READ_EA",
            "DELETE_CHILD",
            "WRITE_ATTR",
            "WRITE_EA",
        ],
    },
]
