ITSM_ATTRIBUTES_FOR_BILLING = [
    "id",
    "sponsor",
    "fileset_name",
    "service_rate_category",
    "amount",
    "funding_number",
    "exempt",
    "subsidized",
    "is_condo_group",
    "parent_id",
    "quota",
    "billing_cycle",
    "billing_contact",
    "status",
    "provision_usage_creation_date",
]
