# Generated by Django 3.2.20 on 2026-05-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0008_auto_20260506_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationattributechangerequest',
            name='old_value',
            field=models.CharField(default='none', max_length=128),
        ),
        migrations.AddField(
            model_name='historicalallocationattributechangerequest',
            name='old_value',
            field=models.CharField(default='none', max_length=128),
        ),
    ]
