# Generated by Django 3.2.20 on 2024-10-02 16:02

from django.db import migrations


def load_initial_data(apps, schema_editor):
    from django.core.management import call_command

    call_command("loaddata", "default_user_groups")


class Migration(migrations.Migration):

    dependencies = [("grant", "0002_auto_20230406_1310")]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
