---
name: 'Trigger Coldfront Rebuild'
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  trigger-coldfront-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: 'coldfront'
          OWNER: 'washu-it-ris'
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: bearer ${GITHUB_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${OWNER}/${REPO}/dispatches \
            -d '{"event_type":"build_and_push_container_images"}'

