---
name: 'Trigger Coldfront Rebuild'
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  trigger-coldfront-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch build_and_push_container_images
        env:
          REPO_NAME: coldfront
          REPO_OWNER: washu-it-ris
          ACCESS_TOKEN: ${{ secret.COLDFRONT_REPO_ACCESS_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: bearer ${ACCESS_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/dispatches \
            -d '{"event_type":"build_and_push_container_images"}'

